#pragma once

//THESE ARE FILLER DEFINITIONS UNTIL PCBA IS DESIGNED
#define WHEEL_SPEED_SENSOR_PIN 1
#define BRAKE_TEMPERATURE_SENSOR_PIN 1
#define SUSPENSION_POSITION_SENSOR_PIN 1

#define BRAKE_TEMPERATURE_SCALAR 1
#define BRAKE_TEMPERATURE_OFFSET 0

#define SUSPENSION_POSITION_SCALAR 1
#define SUSPENSION_POSITION_OFFSET 0